site_name: 前端技术体系总导航
site_description: 前端开发技术文档

# Repository
repo_name: frontend-docs

# Copyright
copyright: Copyright &copy; 2023

# Configuration
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - tables
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - CSS:
    - webs/css/index.md
    - 核心概念:
      - webs/css/box.md
      - webs/css/BFC.md
      - webs/css/dp_px_dpr_ppi.md
      - webs/css/sass_less_stylus.md
    - 布局系统:
      - webs/css/flexbox.md
      - webs/css/grid.md
      - webs/css/column_layout.md
      - webs/css/center.md
    - 视觉呈现:
      - webs/css/animation.md
      - webs/css/css3_features.md
      - webs/css/layout_painting.md
      - webs/css/visual_scrolling.md
    - 实用技巧:
      - webs/css/less_12px.md
      - webs/css/hide_attributes.md
      - webs/css/selector.md
      - webs/css/css_performance.md
      - webs/css/responsive_layout.md
  - JavaScript:
    - webs/JavaScript/index.md
    - 基础概念:
      - webs/JavaScript/data_type.md
      - webs/JavaScript/type_conversion.md
      - webs/JavaScript/scope.md
      - webs/JavaScript/this.md
    - 执行模型:
      - webs/JavaScript/event_loop.md
      - webs/JavaScript/event_Model.md
    - 对象系统:
      - webs/JavaScript/prototype.md
      - webs/JavaScript/new.md
    - 函数编程:
      - webs/JavaScript/functional_programming.md
      - webs/JavaScript/function_cache.md
      - webs/JavaScript/debounce_throttle.md
      - webs/JavaScript/bind_call_apply.md
    - 性能优化:
      - webs/JavaScript/memory_leak.md
      - webs/JavaScript/visible.md
      - webs/JavaScript/tail_recursion.md
  - ES6+:
    - webs/es6/index.md
    - 核心特性:
      - webs/es6/var_let_const.md
      - webs/es6/function.md
      - webs/es6/object.md
      - webs/es6/array.md
    - 异步编程:
      - webs/es6/promise.md
      - webs/es6/generator.md
    - 高级特性:
      - webs/es6/proxy.md
      - webs/es6/set_map.md
      - webs/es6/decorator.md
      - webs/es6/module.md
  - TypeScript:
    - webs/typescript/index.md
    - 基础类型:
      - webs/typescript/basic_types.md
      - webs/typescript/interfaces.md
    - 高级类型:
      - webs/typescript/advanced_types.md
      - webs/typescript/generics.md
    - 工程实践:
      - webs/typescript/namespaces_modules.md
      - webs/typescript/declaration_files.md
  - Vue:
    - webs/vue/index.md
    - 核心概念:
      - webs/vue/lifecycle.md
      - webs/vue/components.md
      - webs/vue/directives.md
    - 状态管理:
      - webs/vue/vuex.md
      - webs/vue/state_management.md
    - 路由与渲染:
      - webs/vue/vue_router.md
      - webs/vue/rendering.md
    - 最佳实践:
      - webs/vue/performance.md
      - webs/vue/testing.md
  - Vue3:
    - webs/vue3/index.md
    - 新特性:
      - webs/vue3/composition_api.md
      - webs/vue3/teleport.md
      - webs/vue3/fragments.md
    - 响应式系统:
      - webs/vue3/reactivity.md
      - webs/vue3/ref_reactive.md
    - 工程化:
      - webs/vue3/vite.md
      - webs/vue3/migration.md
  - React:
    - webs/React/index.md
    - 基础概念:
      - webs/React/JSX_to_DOM.md
      - webs/React/state_props.md
      - webs/React/life_cycle.md
    - 组件设计:
      - webs/React/class_function_component.md
      - webs/React/High_order_components.md
      - webs/React/controlled_Uncontrolled.md
    - 状态管理:
      - webs/React/redux.md
      - webs/React/how_to_use_redux.md
      - webs/React/Redux_Middleware.md
    - Hooks与新特性:
      - webs/React/React_Hooks.md
      - webs/React/Fiber.md
    - 性能优化:
      - webs/React/Improve_performance.md
      - webs/React/diff.md
      - webs/React/key.md
      - webs/React/improve_render.md
  - NodeJS:
    - webs/NodeJS/index.md
    - 核心模块:
      - webs/NodeJS/global.md
      - webs/NodeJS/fs.md
      - webs/NodeJS/Buffer.md
      - webs/NodeJS/Stream.md
      - webs/NodeJS/EventEmitter.md
      - webs/NodeJS/process.md
    - 异步模型:
      - webs/NodeJS/event_loop.md
    - Web开发:
      - webs/NodeJS/middleware.md
      - webs/NodeJS/file_upload.md
      - webs/NodeJS/jwt.md
      - webs/NodeJS/paging.md
    - 性能优化:
      - webs/NodeJS/performance.md
  - Webpack:
    - webs/webpack/index.md
    - 基础配置:
      - webs/webpack/basic_config.md
      - webs/webpack/loaders.md
      - webs/webpack/plugins.md
    - 高级特性:
      - webs/webpack/code_splitting.md
      - webs/webpack/tree_shaking.md
      - webs/webpack/hot_module_replacement.md
    - 性能优化:
      - webs/webpack/performance_optimization.md
      - webs/webpack/bundle_analysis.md
  - HTTP:
    - webs/http/index.md
    - 基础概念:
      - webs/http/GET_POST.md
      - webs/http/status.md
      - webs/http/headers.md
    - 协议演进:
      - webs/http/1.0_1.1_2.0.md
      - webs/http/HTTP_HTTPS.md
      - webs/http/WebSocket.md
    - 网络基础:
      - webs/http/TCP_IP.md
      - webs/http/UDP_TCP.md
      - webs/http/handshakes_waves.md
      - webs/http/DNS.md
      - webs/http/CDN.md
  - Git:
    - webs/git/index.md
    - 基础概念:
      - webs/git/Version_control.md
      - webs/git/HEAD_tree_index.md
    - 常用命令:
      - webs/git/command.md
      - webs/git/git_stash.md
    - 分支管理:
      - webs/git/fork_clone_branch.md
      - webs/git/git_rebase__git_merge.md
      - webs/git/conflict.md
    - 高级操作:
      - webs/git/git_reset__git_revert.md
      - webs/git/git_pull__git_fetch.md
  - Linux:
    - webs/linux/index.md
    - 基础知识:
      - webs/linux/linux.md
      - webs/linux/linux_users.md
    - 文件系统:
      - webs/linux/file.md
    - 进程管理:
      - webs/linux/thread_process.md
    - Shell编程:
      - webs/linux/shell.md
      - webs/linux/redirect_pipe.md
  - 算法:
    - webs/algorithm/index.md
    - 基础概念:
      - webs/algorithm/Algorithm.md
      - webs/algorithm/time_space.md
    - 数据结构:
      - webs/algorithm/structure.md
      - webs/algorithm/Linked_List.md
      - webs/algorithm/stack_queue.md
      - webs/algorithm/tree.md
      - webs/algorithm/graph.md
      - webs/algorithm/set.md
      - webs/algorithm/Heap.md
    - 排序算法:
      - webs/algorithm/sort.md
      - webs/algorithm/bubbleSort.md
      - webs/algorithm/selectionSort.md
      - webs/algorithm/insertionSort.md
      - webs/algorithm/mergeSort.md
      - webs/algorithm/quickSort.md
    - 搜索算法:
      - webs/algorithm/BinarySearch.md
  - 设计模式:
    - webs/design/index.md
    - 创建型模式:
      - webs/design/Singleton_Pattern.md
      - webs/design/Factory__Pattern.md
    - 结构型模式:
      - webs/design/Proxy_Pattern.md
    - 行为型模式:
      - webs/design/Observer__Pattern.md
      - webs/design/Strategy_Pattern.md
  - 小程序:
    - webs/applet/index.md
    - 基础概念:
      - webs/applet/applet.md
      - webs/applet/lifecycle.md
    - 功能实现:
      - webs/applet/login.md
      - webs/applet/navigate.md
      - webs/applet/requestPayment.md
      - webs/applet/WebView_jscore.md
    - 发布与优化:
      - webs/applet/publish.md
      - webs/applet/optimization.md