site_name: 前端技术体系总导航
site_description: 前端开发技术文档
site_author: Frontend Team

# Copyright
copyright: Copyright &copy; 2023 - 2024

# Configuration
theme:
  name: material
  language: zh
  icon:
    logo: material/code-tags
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.path
    # - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frontend-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/frontend-docs

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - tables
  - toc:
      permalink: true
      toc_depth: 3

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

nav:
  - 首页: index.md
  - CSS:
    - webs/css/index.md
    - CSS基础:
      - 基础概念:
        - webs/css/box.md
        - webs/css/BFC.md
        - webs/css/dp_px_dpr_ppi.md
      - 样式处理:
        - webs/css/sass_less_stylus.md
        - webs/css/selector.md
        - webs/css/css3_features.md
    - CSS布局:
      - 视觉效果:
        - webs/css/animation.md
        - webs/css/layout_painting.md
        - webs/css/visual_scrolling.md
    - 布局系统:
      - 弹性盒子布局:
        - webs/css/flexbox.md
      - 网格布局:
        - webs/css/grid.md
      - 多列布局:
        - webs/css/column_layout.md
      - 水平垂直居中:
        - webs/css/center.md
      - 响应式布局:
        - webs/css/responsive_layout.md
    - CSS优化:
      - 性能优化:
        - webs/css/css_performance.md
        - webs/css/less_12px.md
        - webs/css/hide_attributes.md
  - JavaScript:
    - webs/JavaScript/index.md
    - 基础概念:
      - webs/JavaScript/data_type.md
      - webs/JavaScript/type_conversion.md
      - webs/JavaScript/scope.md
      - webs/JavaScript/this.md
    - 执行模型:
      - webs/JavaScript/event_loop.md
      - webs/JavaScript/event_Model.md
    - 对象系统:
      - webs/JavaScript/prototype.md
      - webs/JavaScript/new.md
    - 函数编程:
      - webs/JavaScript/functional_programming.md
      - webs/JavaScript/function_cache.md
      - webs/JavaScript/debounce_throttle.md
      - webs/JavaScript/bind_call_apply.md
    - 性能优化:
      - webs/JavaScript/memory_leak.md
      - webs/JavaScript/visible.md
      - webs/JavaScript/tail_recursion.md
  - ES6+:
    - webs/es6/index.md
    - 基础语法:
      - webs/es6/var_let_const.md
      - webs/es6/function.md
      - webs/es6/object.md
      - webs/es6/array.md
    - 异步编程:
      - webs/es6/promise.md
      - webs/es6/generator.md
    - 数据结构:
      - webs/es6/set_map.md
    - 高级特性:
      - webs/es6/proxy.md
      - webs/es6/decorator.md
      - webs/es6/module.md
  - TypeScript:
    - webs/typescript/index.md
    - 类型系统:
      - webs/typescript/data_type.md
      - webs/typescript/high_type.md
      - webs/typescript/interface.md
      - webs/typescript/enum.md
    - 函数与泛型:
      - webs/typescript/function.md
      - webs/typescript/generic.md
    - 装饰器:
      - webs/typescript/decorator.md
      - webs/typescript/class.md
    - 模块系统:
      - webs/typescript/namespace_module.md
    - 与框架集成:
      - webs/typescript/vue.md
      - webs/typescript/react.md
    - 比较研究:
      - webs/typescript/typescript_javascript.md
  - Vue:
    - webs/vue/index.md
    - 基础概念:
      - webs/vue/new_vue.md
      - webs/vue/data.md
      - webs/vue/data_object_add_attrs.md
      - webs/vue/lifecycle.md
      - webs/vue/if_for.md
      - webs/vue/show_if.md
    - 组件系统:
      - webs/vue/components_plugin.md
      - webs/vue/communication.md
      - webs/vue/slot.md
      - webs/vue/vnode.md
    - 响应式机制:
      - webs/vue/observable.md
      - webs/vue/nexttick.md
      - webs/vue/keepalive.md
    - 功能扩展:
      - webs/vue/mixin.md
      - webs/vue/directive.md
      - webs/vue/modifier.md
      - webs/vue/filter.md
      - webs/vue/bind.md
    - 性能优化:
      - webs/vue/first_page_time.md
      - webs/vue/diff.md
      - webs/vue/key.md
    - 网络与请求:
      - webs/vue/axios.md
      - webs/vue/axiosCode.md
      - webs/vue/cors.md
    - 工程实践:
      - webs/vue/structure.md
      - webs/vue/error.md
      - webs/vue/permission.md
      - webs/vue/spa.md
      - webs/vue/ssr.md
      - webs/vue/vue.md
    - 版本对比:
      - webs/vue/vue3_vue2.md
  - Vue3:
    - webs/vue3/index.md
    - 基础架构:
      - webs/vue3/goal.md
      - webs/vue3/composition.md
      - webs/vue3/proxy.md
    - 性能优化:
      - webs/vue3/performance.md
      - webs/vue3/treeshaking.md
    - 组件设计:
      - webs/vue3/modal_component.md
  - React:
    - webs/React/index.md
    - 基础概念:
      - webs/React/JSX_to_DOM.md
      - webs/React/state_props.md
      - webs/React/life_cycle.md
    - 组件设计:
      - webs/React/class_function_component.md
      - webs/React/High_order_components.md
      - webs/React/controlled_Uncontrolled.md
    - 状态管理:
      - webs/React/redux.md
      - webs/React/how_to_use_redux.md
      - webs/React/Redux_Middleware.md
    - Hooks与新特性:
      - webs/React/React_Hooks.md
      - webs/React/Fiber.md
    - 性能优化:
      - webs/React/Improve_performance.md
      - webs/React/diff.md
      - webs/React/key.md
      - webs/React/improve_render.md
  - NodeJS:
    - webs/NodeJS/index.md
    - 核心模块:
      - webs/NodeJS/global.md
      - webs/NodeJS/fs.md
      - webs/NodeJS/Buffer.md
      - webs/NodeJS/Stream.md
      - webs/NodeJS/EventEmitter.md
      - webs/NodeJS/process.md
    - 异步模型:
      - webs/NodeJS/event_loop.md
    - Web开发:
      - webs/NodeJS/middleware.md
      - webs/NodeJS/file_upload.md
      - webs/NodeJS/jwt.md
      - webs/NodeJS/paging.md
    - 性能优化:
      - webs/NodeJS/performance.md
  - Webpack:
    - webs/webpack/index.md
    - 基础配置:
      - webs/webpack/basic_config.md
      - webs/webpack/loaders.md
      - webs/webpack/plugins.md
      - webs/webpack/build_process.md
    - 高级特性:
      - webs/webpack/code_splitting.md
      - webs/webpack/tree_shaking.md
      - webs/webpack/hot_module_replacement.md
      - webs/webpack/Loader_Plugin.md
      - webs/webpack/proxy.md
    - 性能优化:
      - webs/webpack/performance_optimization.md
      - webs/webpack/bundle_analysis.md
      - webs/webpack/improve_build.md
    - 生态与对比:
      - webs/webpack/webpack.md
      - webs/webpack/Rollup_Parcel_snowpack_Vite.md
  - HTTP:
    - webs/http/index.md
    - 基础概念:
      - webs/http/GET_POST.md
      - webs/http/status.md
      - webs/http/headers.md
    - 协议演进:
      - webs/http/1.0_1.1_2.0.md
      - webs/http/HTTP_HTTPS.md
      - webs/http/WebSocket.md
    - 网络基础:
      - webs/http/TCP_IP.md
      - webs/http/UDP_TCP.md
      - webs/http/handshakes_waves.md
      - webs/http/DNS.md
      - webs/http/CDN.md
  - Git:
    - webs/git/index.md
    - 基础概念:
      - webs/git/Version_control.md
      - webs/git/HEAD_tree_index.md
    - 常用命令:
      - webs/git/command.md
      - webs/git/git_stash.md
    - 分支管理:
      - webs/git/fork_clone_branch.md
      - webs/git/git_rebase__git_merge.md
      - webs/git/conflict.md
    - 高级操作:
      - webs/git/git_reset__git_revert.md
      - webs/git/git_pull__git_fetch.md
  - Linux:
    - webs/linux/index.md
    - 基础知识:
      - webs/linux/linux.md
      - webs/linux/linux_users.md
    - 文件系统:
      - webs/linux/file.md
    - 进程管理:
      - webs/linux/thread_process.md
    - Shell编程:
      - webs/linux/shell.md
      - webs/linux/redirect_pipe.md
  - 算法:
    - webs/algorithm/index.md
    - 基础概念:
      - webs/algorithm/Algorithm.md
      - webs/algorithm/time_space.md
    - 数据结构:
      - webs/algorithm/structure.md
      - webs/algorithm/Linked_List.md
      - webs/algorithm/stack_queue.md
      - webs/algorithm/tree.md
      - webs/algorithm/graph.md
      - webs/algorithm/set.md
      - webs/algorithm/Heap.md
    - 排序算法:
      - webs/algorithm/sort.md
      - webs/algorithm/bubbleSort.md
      - webs/algorithm/selectionSort.md
      - webs/algorithm/insertionSort.md
      - webs/algorithm/mergeSort.md
      - webs/algorithm/quickSort.md
    - 搜索算法:
      - webs/algorithm/BinarySearch.md
  - 设计模式:
    - webs/design/index.md
    - 创建型模式:
      - webs/design/Singleton_Pattern.md
      - webs/design/Factory__Pattern.md
    - 结构型模式:
      - webs/design/Proxy_Pattern.md
    - 行为型模式:
      - webs/design/Observer__Pattern.md
      - webs/design/Strategy_Pattern.md
  - 小程序:
    - webs/applet/index.md
    - 基础概念:
      - webs/applet/applet.md
      - webs/applet/lifecycle.md
    - 功能实现:
      - webs/applet/login.md
      - webs/applet/navigate.md
      - webs/applet/requestPayment.md
      - webs/applet/WebView_jscore.md
    - 发布与优化:
      - webs/applet/publish.md
      - webs/applet/optimization.md