site_name: 前端技术体系总导航
site_description: 前端开发技术文档

# Repository
repo_name: frontend-docs

# Copyright
copyright: Copyright &copy; 2023

# Configuration
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - tables
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - CSS:
    - webs/css/index.md
    - 核心概念:
      - webs/css/box.md
      - webs/css/BFC.md
      - webs/css/dp_px_dpr_ppi.md
      - webs/css/sass_less_stylus.md
    - 布局系统:
      - webs/css/flexbox.md
      - webs/css/grid.md
      - webs/css/column_layout.md
      - webs/css/center.md
    - 视觉呈现:
      - webs/css/animation.md
      - webs/css/css3_features.md
      - webs/css/layout_painting.md
      - webs/css/visual_scrolling.md
    - 实用技巧:
      - webs/css/less_12px.md
      - webs/css/hide_attributes.md
      - webs/css/selector.md
      - webs/css/css_performance.md
      - webs/css/responsive_layout.md
  - JavaScript:
    - webs/JavaScript/index.md
    - 基础概念:
      - webs/JavaScript/data_type.md
      - webs/JavaScript/type_conversion.md
      - webs/JavaScript/scope.md
      - webs/JavaScript/this.md
    - 执行模型:
      - webs/JavaScript/event_loop.md
      - webs/JavaScript/event_Model.md
    - 对象系统:
      - webs/JavaScript/prototype.md
      - webs/JavaScript/new.md
    - 函数编程:
      - webs/JavaScript/functional_programming.md
      - webs/JavaScript/function_cache.md
      - webs/JavaScript/debounce_throttle.md
      - webs/JavaScript/bind_call_apply.md
    - 性能优化:
      - webs/JavaScript/memory_leak.md
      - webs/JavaScript/visible.md
      - webs/JavaScript/tail_recursion.md
  - ES6+:
    - webs/es6/index.md
  - TypeScript:
    - webs/typescript/index.md
  - Vue:
    - webs/vue/index.md
  - Vue3:
    - webs/vue3/index.md
  - React:
    - webs/React/index.md
  - NodeJS:
    - webs/NodeJS/index.md
  - Webpack:
    - webs/webpack/index.md
  - HTTP:
    - webs/http/index.md
  - Git:
    - webs/git/index.md
  - Linux:
    - webs/linux/index.md
  - 算法:
    - webs/algorithm/index.md
  - 设计模式:
    - webs/design/index.md
  - 小程序:
    - webs/applet/index.md  