name: Deploy MkDocs site  # 工作流的名称：部署MkDocs站点

on:  # 定义触发工作流的事件
  push:  # 当推送代码时触发
    branches:  # 指定触发工作流的分支
      - main  # 设置在推送到main分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:  # 定义工作流中的作业
  deploy:  # 作业名称：部署
    runs-on: ubuntu-latest  # 指定运行环境为最新版本的Ubuntu
    steps:  # 定义作业中的步骤
      - name: Checkout repository  # 步骤名称：检出代码仓库
        uses: actions/checkout@v3  # 使用GitHub官方的checkout动作的v3版本
        with:  # 配置checkout动作的参数
          fetch-depth: 0  # 获取所有历史记录，而不是仅获取最近的提交

      - name: Set up Python  # 步骤名称：设置Python环境
        uses: actions/setup-python@v4  # 使用GitHub官方的setup-python动作的v4版本
        with:  # 配置setup-python动作的参数
          python-version: '3.x'  # 使用最新的Python 3版本

      - name: Install dependencies  # 步骤名称：安装依赖
        run: |  # 运行以下命令
          python -m pip install --upgrade pip  # 升级pip到最新版本
          pip install mkdocs-material  # 安装mkdocs-material主题
          pip install mkdocs  # 安装mkdocs
          # 如果有其他依赖，请在这里添加  # 注释：提示可以在此处添加其他依赖

      - name: Build and deploy  # 步骤名称：构建并部署
        run: |  # 运行以下命令
          mkdocs gh-deploy --force --clean --verbose  # 使用mkdocs命令部署到GitHub Pages，--force强制推送，--clean清理旧文件，--verbose显示详细输出